export const LOAD_USERS = 'LOAD_USERS';
export const LOAD_COMPETITION_TABLE = 'LOAD_COMPETITION_TABLE';
export const UPDATE_USERS_LOADED_FLAG = 'UPDATE_USERS_LOADED_FLAG';
export const UPDATE_COMPETITION_TABLE_LOADED_FLAG = 'UPDATE_COMPETITION_TABLE_LOADED_FLAG';
