env:
  browser: true
  es6: true
  node: true
extends:
  - 'plugin:vue/essential'
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - vue
rules:
  indent:
    - error
    - 4
  no-param-reassign:
    - error
    - props: true
      ignorePropertyModificationsFor:
        - state
  max-len:
    - warn
